name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Project
        run: mvn clean compile

      - name: Run Tests
        run: mvn test

      - name: Package WAR
        run: mvn package

      - name: SonarQube Scan
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=trainbook \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Upload Artifact
        run: mvn deploy

      - name: Deploy To Tomcat
        run: |
          curl -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
          -T target/*.war \
          "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"
